# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'watchwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1413, 1033)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 50, 1281, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget)
        self.label_33.setEnabled(True)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout.addWidget(self.label_33)
        self.pushButton_debug_model = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_debug_model.setObjectName("pushButton_debug_model")
        self.horizontalLayout.addWidget(self.pushButton_debug_model)
        self.pushButton_control_model = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_control_model.setObjectName("pushButton_control_model")
        self.horizontalLayout.addWidget(self.pushButton_control_model)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(727, 90, 611, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_chart = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_chart.setObjectName("checkBox_chart")
        self.horizontalLayout_2.addWidget(self.checkBox_chart)
        self.comboBox_data = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_data.setMinimumSize(QtCore.QSize(299, 0))
        self.comboBox_data.setObjectName("comboBox_data")
        self.horizontalLayout_2.addWidget(self.comboBox_data)
        self.pushButton_data_output = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_data_output.setObjectName("pushButton_data_output")
        self.horizontalLayout_2.addWidget(self.pushButton_data_output)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(60, 150, 1281, 831))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_33.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">观测窗口</span></p></body></html>"))
        self.pushButton_debug_model.setText(_translate("Form", "调试模式"))
        self.pushButton_control_model.setText(_translate("Form", "控制模式"))
        self.checkBox_chart.setText(_translate("Form", "折线图"))
        self.pushButton_data_output.setText(_translate("Form", "导出数据"))
